spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=project
spring.datasource.password=project
spring.jpa.hibernate.ddl-auto=update
app.cors.allowed-origins=http://localhost:3000